name: Build with PyInstaller

on:
  push:
    tags:
      - 'v*'  # Trigger workflow on version tags (e.g., v1.0.0)

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'  

    - name: Install PyInstaller
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Compile the spec file
      run: |
        pyinstaller test.spec
    
    - name: Extract Tag Name
      id: extract_tag_name
      run:
        $tagName = $Env:GITHUB_REF -replace 'refs/tags/', ''

    - name: Create ZIP package  
      run: |
          mkdir release
          cd release
           zip -r release.zip 
    

    - name: Create Release
      id: upload_asset
      uses: softprops/action-gh-release@v1
      with:
            files: "release/*"
            name: ${{ steps.extract_tag_name.outputs.tag_name }}
            tag_name: ${{ steps.extract_tag_name.outputs.tag_name }}
            draft: false
            prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}       
            
